--- #YAML:1.0
name: Finance-Currency-Convert-WebserviceX
abstract: Lightweight currency conversion using WebserviceX.NET
author: Christopher H. Laco <claco@chrislaco.com>
version: 0.05
version_from: lib\Finance\Currency\Convert\WebserviceX.pm
installdirs: site
license: perl
requires:
  LWP: 0
  HTTP::Response: 0
recommends:
  Pod::Coverage: 0.14
  Test::Pod: 1.00
  Test::Pod::Coverage: 1.04
  Test:Strict: 0.05
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
